In [33]:
import numpy as np

* numpy is used for big operations
* consumes less memory and is faster than lists
* same data type

In [34]:
# one-dimensional array
a = np.array([5,5,5,5,5])
a

array([5, 5, 5, 5, 5])

In [35]:
type(a)

numpy.ndarray

In [36]:
# two-dimensional array
b = np.array([[5,5,5,5,5], [2,2,2,2,2]])
b

array([[5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2]])

In [37]:
type(b)

numpy.ndarray

- **Vector:** an array with a single dimension
- **Matrix:** an array with two dimensions
- **Tensors:** an array with three dimensions

**Dimensions are called axis**
* 1st axis is top to bottom
* 2nd axis is right to left

In [38]:
len(b)

2

# Creating 1-D Array

In [39]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [40]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [41]:
c = np.ones(3)
c

array([1., 1., 1.])

In [42]:
d = np.empty(3)
d

array([1., 1., 1.])

In [43]:
# making an array by giving a range staring from 0
e = np.arange(8)
e

array([0, 1, 2, 3, 4, 5, 6, 7])

In [44]:
# making an array by giving a specific range
f = np.arange(13,34)
f

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33])

In [45]:
# making an array by giving a specific range BUT with a difference in numbers
# below we need an array from 10 to 30 with numbers haivng gap or difference if 2 between them
g = np.arange(10, 30, 2)
g


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [46]:
# linearly spaced arrays
h = np.linspace(10, 40, num = 5)
h

array([10. , 17.5, 25. , 32.5, 40. ])

In [47]:
i = np.ones(5, dtype = np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [48]:
j = np.array([[2,5,1,5],[2,5,7,1]], dtype = np.int8)
j

array([[2, 5, 1, 5],
       [2, 5, 7, 1]], dtype=int8)

In [49]:
menu = np.array(["Pizza", "Burger", "Pasta", "Coffee"])
menu

array(['Pizza', 'Burger', 'Pasta', 'Coffee'], dtype='<U6')

In [50]:
price = np.array([30, 24, 26, 6])
price

array([30, 24, 26,  6])

In [51]:
price.mean()

21.5

In [53]:
a = np.array([2,4,25,364,225,82,55,7,8])
a.sort()
a

array([  2,   4,   7,   8,  25,  55,  82, 225, 364])

# 2-D array

In [54]:
a = np.array([
    [2,6,12,75,13],
    [5,75,45,932,1]
])
a

array([[  2,   6,  12,  75,  13],
       [  5,  75,  45, 932,   1]])

In [56]:
b = np.array([
    [32,421,64,86,14],
    [24,64,23,81,131]
])
b

array([[ 32, 421,  64,  86,  14],
       [ 24,  64,  23,  81, 131]])

In [63]:
c = np.concatenate((a,b), axis = 0)
c

array([[  2,   6,  12,  75,  13],
       [  5,  75,  45, 932,   1],
       [ 32, 421,  64,  86,  14],
       [ 24,  64,  23,  81, 131]])

In [64]:
c = np.concatenate((a,b), axis = 1)
c

array([[  2,   6,  12,  75,  13,  32, 421,  64,  86,  14],
       [  5,  75,  45, 932,   1,  24,  64,  23,  81, 131]])

# 3-D array

In [67]:
d = np.array([
    [[32,421,64,86,14],
    [24,64,23,81,131]],
    
    [[2,6,12,75,13],
    [5,75,45,932,1]],
    
    [[4, 34, 75, 24, 64],
    [41,64,767, 34,134]]
])
d

array([[[ 32, 421,  64,  86,  14],
        [ 24,  64,  23,  81, 131]],

       [[  2,   6,  12,  75,  13],
        [  5,  75,  45, 932,   1]],

       [[  4,  34,  75,  24,  64],
        [ 41,  64, 767,  34, 134]]])

In [68]:
d.ndim

3