In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd


/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: l

In [3]:
print(tf.__version__)

2.12.0


In [4]:
# Sqeuential Layer of Neural Network

model = tf.keras.Sequential([keras.layers.Dense(units = 1, input_shape=[1])])

In [5]:
model.compile(optimizer='sgd', loss="mean_squared_error")

In [6]:
# make nupy arrays for data
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype = float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype = float)

In [7]:
model.fit(xs, ys, epochs = 50)

Epoch 1/50
1/1 [==============================] - 6s 6s/step - loss: 37.6947
Epoch 2/50
1/1 [==============================] - 0s 7ms/step - loss: 30.0019
Epoch 3/50
1/1 [==============================] - 0s 7ms/step - loss: 23.9425
Epoch 4/50
1/1 [==============================] - 0s 9ms/step - loss: 19.1683
Epoch 5/50
1/1 [==============================] - 0s 8ms/step - loss: 15.4053
Epoch 6/50
1/1 [==============================] - 0s 8ms/step - loss: 12.4382
Epoch 7/50
1/1 [==============================] - 0s 7ms/step - loss: 10.0972
Epoch 8/50
1/1 [==============================] - 0s 8ms/step - loss: 8.2491
Epoch 9/50
1/1 [==============================] - 0s 7ms/step - loss: 6.7888
Epoch 10/50
1/1 [==============================] - 0s 7ms/step - loss: 5.6338
Epoch 11/50
1/1 [==============================] - 0s 7ms/step - loss: 4.7190
Epoch 12/50
1/1 [==============================] - 0s 8ms/step - loss: 3.9935
Epoch 13/50
1/1 [==============================] - 0s 7ms/step - lo

In [8]:
print(model.predict([10]))

1/1 [==============================] - 0s 100ms/step
[[16.588844]]


In [9]:
print(model.predict([11]))

1/1 [==============================] - 0s 38ms/step
[[18.242348]]


In [11]:
 print(tf.__version__)

2.12.0


# **Creating Tensors**

In [12]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

# **Rank/Degree of tensors**

In [13]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [14]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# **Shape of Tensors**

In [15]:
rank2_tensor.shape

TensorShape([2, 2])

# **Channging Shape**

In [16]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

In [17]:
tensor1.shape

TensorShape([1, 2, 3])

In [18]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
